language: 
 - php

env:
 - PHPUNIT_VERSION=4.8.*

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - 7.1
 - hhvm

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-interaction --no-update

install: 
  - travis_retry composer update --prefer-source --no-interaction

script: 
 - cd tests
 - ../vendor/bin/phpunit'
